### ISSUE TITLE
Authorization endpoint

### ISSUE THREAD

**Issue by flabbyThoroughbred** [zeekhoo-okta/okta-django-samples#15]
Hi,

Where in the code is the authorization endpoint being used? I think it's coming from the DocumentDiscovery method but I don't see authorization_endpoint being invoked.

The reason I ask is that I'm getting a 500 error after authenticating:
https://mysite.com/oidc/callback?state=Gihv7byIRJUD1iEDneM8Oi00SH1I4quwYjTOZEE7bKNyXgWlH7RzsdOqNscd4O5q&error=access_denied&error_description=Policy+evaluation+failed+for+this+request%2C+please+check+the+policy+configurations.

I don't recall this happening before but I'm exactly sure how to deal with it.
from my issuer "https://my.okta.com/oauth2/default/.well-known/openid-configuration"
the authorization_endpoint is "https://my.okta.com/oauth2/default/v1/authorize" however I'm not certain the default is necessary. (I've tried this on a flask web app authenticating oidc and I receive so no access denied errors).

Any clue what might be causing this? I'm afraid I may be chasing the wrong problem here.

Thanks!

**Comment by zeekhoo** [comment]
Hi Mark,

Notice there's an error returned as a query param: `error=access_denied&error_description=Policy+evaluation+failed+for+this+request%2C+please+check+the+policy+configurations.`
i.e. "The Policy evaluation failed for this request. Please check the policy configurations".

**What this means:**
With Okta, you can configure the AuthorizationServer to accept/reject certain types of requests (for example, do not allow `authorization_code` flow). Do you recall changing the settings on the `default` AuthServer? Normally, it is set to "allow all grants", "allow all scopes", and "allow anyone". But you may have changed that. (I'm also assuming you're still using the `default` AuthServer, based on your comments).

For more info see the full documentation [here](https://help.okta.com/en/prod/Content/Topics/Security/API_Access.htm)
Double-check your settings to make sure you're not rejecting the type of request the sample code is making. For Django, as per this sample, we are using `authorization_code` flow.

_Per the second question, here's what you need to know:_
* If your issuer is `https://my.okta.com/oauth2/default` (as I believe it is), then your authorization endpoint should be `"https://my.okta.com/oauth2/default/v1/authorize`....i.e. `default` should be in the authorize endpoint because it is in the issuer uri.
* Note that all the OAuth endpoints have the same `host` and `path` as the issuer uri (Everything up to the `/v1/`). You should be able to see the OAuth endpoints when you hit `https://my.okta.com/oauth2/default/.well-known/openid-configuration`
* Here's some more [information](https://developer.okta.com/docs/concepts/auth-servers/).

Hope this helps you track down the issues. But let me know if the AuthServer settings was the issue or not and we can go from there.

**Comment by flabbyThoroughbred** [comment]
per the https://my.okta.com/oauth2/default/.well-known/openid-configuration:
"grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"]

In this case, does this look valid?

**Comment by zeekhoo** [comment]
Not really. The .well-known endpoint can't exactly tell you which grants are valid for the authorization request that was made. That's because it doesn't know what your request parameters are. You need to look in the Okta UI and check what your configuration is. Navigate to Security > API > Authorization Servers. Choose the `default` one. And navigate to the "Access Policies" tab:

<img width="1031" alt="Screen Shot 2021-03-26 at 4 29 31 PM" src="https://user-images.githubusercontent.com/10700898/112702365-7831f580-8e50-11eb-9c71-315dfb0f1f68.png">

Inspect your rules. 

Try the "Token Preview" tab to debug your rules. It usually helps nail the rule mis-configuration.

**Comment by flabbyThoroughbred** [comment]
Thanks! I'll check with the team that manages this.

**Comment by flabbyThoroughbred** [comment]
That did it. Thanks!
