### ISSUE TITLE
KeyError at /oauth2/callback

### ISSUE THREAD

**Issue by althelion** [zeekhoo-okta/okta-django-samples#24]
![image](https://user-images.githubusercontent.com/53283900/122679542-dab34b80-d21d-11eb-9d38-a1182941aa16.png)

I'm receiving error after login > callback. Since these values are not visible
        cookie_state = request.COOKIES["okta-oauth-state"]
        cookie_nonce = request.COOKIES["okta-oauth-nonce"]

**Comment by althelion** [comment]
Here's my browser settings for cookies 

![image](https://user-images.githubusercontent.com/53283900/122679862-20244880-d21f-11eb-9a5a-42e0c92970ec.png)

**Comment by zeekhoo** [comment]
I see that you're hitting http://127.0.0.1:8000. Try using http://localhost:8000, which is what I've defaulted the project to run on.

**Comment by althelion** [comment]
ok verified that localhost:8000 is working .. 
hmm not sure why 127.0.0.1:8000 is not.

**Comment by althelion** [comment]
thank you

**Comment by crunchmasterdeluxe** [comment]
Hi! Thanks for putting this project together. Awesome package if I can get it to work for me.
I have tried this in Firefox and Chrome, locally on both http and https, and using both localhost and 127.0.0.1 in all files and references. I always get this error:
500 error: `okta_oauth_state` key error from the line `cookie_state = request.COOKIES["okta-oauth-state"]` in views.callback_controller() (same error as mentioned above).

If I change the login redirect uri in Okta admin so that it returns a 400 error due to a mismatch with my settings.py, I can see the okta_oauth_state and nonce cookies in the browser. However, if the 400 error does not occur, okta_oauth_state is nowhere to be found in my cookies. Any ideas?

**Comment by zeekhoo** [comment]
Hi - I'm no longer Okta and this project is hardly maintained though it
doesn't need to be. Just to make sure nothing has changed with Okta's
service, I signed up for a brand new Okta developer account to try this
project out again; Brand new clone of the repo too. Sure enough, everything
still works! Also, I'm using Chrome for this.

I can't think of anything off the top of my head -- Your 400 error seems
suspicious though, since I don't see that issue on my end. Did you say that
there's a situation when you get the 400 and when you don't or did I
misunderstand? If so, how does the 400 occur and in what situation does it
not?

-Zee

**Comment by crunchmasterdeluxe** [comment]
Thanks for the response and for looking into this!
Sorry, I edited my original comment. My issue is just the 500 error:
![Screen Shot 2022-08-24 at 5 09 08 PM](https://user-images.githubusercontent.com/83776204/186539190-16e96b62-1101-4131-b071-333711a17867.png)
 The only cookies in the request are `username-localhost-8888`,  `_xsrf`, and `csrftoken`. It's strange though because  when I change my redirect login uri in Okta to force a 400 error, the okta_oauth cookies appear in the request cookies. Any idea what could affect that? I imagine that the js widget is producing those cookies.

**Comment by zeekhoo** [comment]
You're correct. state and nonce are generated by the widget, then they are
parameters to the /authorize request, which you can see in the screenshot
below.
(You should have landed on this page if you successfully logged in)
[image: Screen Shot 2022-08-24 at 5.03.41 PM.png]

Cookies are returned in the redirect to the /callback endpoint:
[image: Screen Shot 2022-08-24 at 5.09.51 PM.png]
Not sure how you're seeing those other cookies. What edition of Okta are
you using? Maybe you're missing some features.

-Zee

**Comment by zeekhoo** [comment]
Maybe you're blocking 3rd party cookies:

[image: Screen Shot 2022-08-24 at 5.24.36 PM.png]
