### ISSUE TITLE
CORS access issue

### ISSUE THREAD

**Issue by tuyiskevin** [zeekhoo-okta/okta-django-samples#28]
@zeekhoo, @westsaharut , & @deadbeef404 
I've been trying to run this sample app locally and have set up everything as directed in the README.md but I keep getting this error

`Access to XMLHttpRequest at 'http://dev-6764913.okta.com/api/v1/authn' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
POST http://dev-6764913.okta.com/api/v1/authn net::ERR_FAILED
 XHR failed loading: POST "http://dev-6764913.okta.com/api/v1/authn".`

Any thoughts?

**Comment by zeekhoo** [comment]
@tuyiskevin - There's security policies in Okta you can configure to allow [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Login to your Okta tenant (https://dev-6764913.okta.com) and look under Security > API > TrustedOrigins.

**Comment by tuyiskevin** [comment]
@zeekhoo I thought that was the issue but even after adding the trusted origins it keeps on failing
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/46584393/158226194-c5dd26b6-cb7d-4d13-b8cf-d8b5f3280175.png">

I was wondering if I need to generate an API token and add it to the header

**Comment by zeekhoo** [comment]
I see a trailing slash at the end of localhost:8000. I think it needs to be removed. CORS headers settings must be exact matches.

**Comment by tuyiskevin** [comment]
I removed it and re-run the app again and it still gives the same error.
if you still have this running on your local, do you get this type of error? I know the project was created a while ago and was thinking it might be due to a change in the okta api

**Comment by zeekhoo** [comment]
I just tested with Chrome, Firefox and Safari with no issues. Also tried a negative test (removed my CORS settings in Okta) and I do get the CORS error as expected. All else being equal, it could be your browser settings that's causing the issues. I also note that your error message `Access to XMLHttpRequest at 'http://dev-6764913.okta.com/api/v1/authn' from origin 'http://localhost:8000'...` looks a bit strange as it is reporting your request going to `http` instead of `https//dev-6764913.okta.com/api/v1/authn`

**Comment by tuyiskevin** [comment]
you're right! It's working now. I'd `http://` instead of `https://`
Thanks for all the help! I really appreciate it!
